[package]
name = "ecm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
num-bigint = { version = "0.4.3", features = [ "rand" ] }
pretty_env_logger = "0.4.0"
rand = "0.8.5"
