[package]
name = "ecm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-backtrace = "0.5.1"
colored = "2.0.0"
log = "0.4.17"
num-bigint = { version = "0.4.3", features = [ "rand" ] }
num-integer = "0.1.45"
num-traits = "0.2.15"
pretty_env_logger = "0.4.0"
primes = "0.3.0"
rand = "0.8.5"
